### ISSUE TITLE
parquet + object-store

### ISSUE THREAD

**Issue by drernie** [quiltdata/quilt-rs#3]
Use https://github.com/apache/arrow-rs (Parquet + Object Store) to:

1. Read and parse the QuiltCore.py [Parquet manifest](https://quilt-t4-staging.quiltdata.com/b/udp-spec/tree/.quilt/packages/122045ee6d96fd1cd8d1555e2d86e7e4a1699c05eeba9a555a4ea789004816abb592.parquet) 
2. Read the versioned physical keys (if possible)
`s3://udp-spec/spec/parquet/READ ME.md?versionId=r5iu2bKoYyeUUt5veiBM8yfLRgu06fe7`

Without directly calling the S3 SDK!

**Comment by drernie** [comment]
- https://quilt-t4-staging.quiltdata.com/b/udp-spec/tree/.quilt/packages/122045ee6d96fd1cd8d1555e2d86e7e4a1699c05eeba9a555a4ea789004816abb592.parquet
- https://quilt-t4-staging.quiltdata.com/b/udp-spec/packages/spec/parquet
- https://quilt-t4-staging.quiltdata.com/b/udp-spec/packages/spec/parquet/tree/45ee6d96fd1cd8d1555e2d86e7e4a1699c05eeba9a555a4ea789004816abb592/READ%20ME.md
- VersionId: "r5iu2bKoYyeUUt5veiBM8yfLRgu06fe7"
-

**Comment by sir-sigurd** [comment]
https://github.com/quiltdata/quilt-rs/blob/object-store-parquet/src/main.rs

**Comment by drernie** [comment]
@sir-sigurd I have a "[Table](https://github.com/quiltdata/quilt-rs/blob/main/src/quilt4/table.rs)" stub if you want to take a stab at making it read Parquet into a RecordBatch (instead of Vec<Row>).

**Comment by drernie** [comment]
Ooh! Unlike Java (but like Python) Arrow also has a [JSON Importer](https://arrow.apache.org/rust/arrow_json/index.html).

What I did for QuiltCore was read in JSON, then transform the "Table3" to mirror the native "Table4" Parquet.

**Comment by drernie** [comment]
You can test using `tests/test_domain/.quilt/packages/12201234.parquet` - which should be `utils::local_uri_parquet()` but sometimes is not...

**Comment by drernie** [comment]
Saving the [RecordBatch Reader](https://arrow.apache.org/rust/parquet/arrow/arrow_reader/index.html) link, because I had great difficulty finding it. 

I wonder if the [Predicate](https://arrow.apache.org/rust/parquet/arrow/arrow_reader/trait.ArrowPredicate.html) would allow us to decode on import...

**Comment by sir-sigurd** [comment]
> I wonder if the [Predicate](https://arrow.apache.org/rust/parquet/arrow/arrow_reader/trait.ArrowPredicate.html) would allow us to decode on import...

what exactly do you mean by "decode" here?

**Comment by drernie** [comment]
Convert quilt3 names and values into their quilt4 equivalents, particularly:
1.  Convert urlencoded physical_key arrays into a single "place"
2. Convert Hash structs into a single multi hash string

I.e., all the "quilt3.schema" parameters in [quiltcore](https://github.com/quiltdata/quiltcore/blob/main/quiltcore/config/quiltcore.yaml).

**Comment by drernie** [comment]
@sir-sigurd Do you have time to finish Dima's work, and implement read4 for S3.object_path/bucket?

**Comment by sir-sigurd** [comment]
> @sir-sigurd Do you have time to finish Dima's work, and implement read4 for S3.object_path/bucket?

do we have stub for this? or at least at what file?

**Comment by sir-sigurd** [comment]
> > @sir-sigurd Do you have time to finish Dima's work, and implement read4 for S3.object_path/bucket?
> 
> do we have stub for this? or at least at what file?

anyway it looks like I don't have time for it today

**Comment by drernie** [comment]
@dimaryaz Can you let Sergey know when and where you stopped, and perhaps suggest what it would be helpful for him to work on next?
